shared-version = true
tag-name = "v{{version}}"
pre-release-replacements = [
    {file="../CHANGELOG.md", search="# Unreleased", replace="# {{version}} ({{date}})", exactly=1},
    {file="../CHANGELOG.md", search="\\.\\.\\.main", replace="...v{{version}}", exactly=1},
    {file="../CHANGELOG.md", search="\\A", replace="# Unreleased\n\n[Full changelog](https://github.com/badboy/signify-rs/compare/v{{version}}...main)\n\n", exactly=1}
]
