[package]
name = "signify"
version = "0.4.1"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>", "BlackHoleFox <blackholefoxdev@gmail.com>"]
edition = "2021"

keywords = ["cryptography", "security"]
description = "Command-line implementation of the signify signature scheme"

readme = "../README.md"
license = "MIT"

homepage = "https://github.com/badboy/signify-rs"
repository = "https://github.com/badboy/signify-rs"

[[bin]]
name = "signify"
doc = false

[dependencies]
clap = { version = "3.0.0-beta.5", default-features = false, features = ["cargo", "derive", "std"] }
rand_core = { version = "0.5", features = ["getrandom"] }
rpassword = "5"
libsignify = { path = "../libsignify" } 